# Krushak App - Strict Analysis Configuration
# This file configures the analyzer for production-ready code quality

include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # Strict rules for production code
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # Error prevention
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    
    # Code quality
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_function_declarations_over_variables: true
    
    # Documentation
    public_member_api_docs: false  # Set to true for library packages
    
    # Style
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    
    # Flutter specific
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    
    # Performance
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_collection_literals: true
    prefer_contains: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_spread_collections: true
    
    # Security & Safety
    avoid_catching_errors: true
    avoid_types_as_parameter_names: true
    no_duplicate_case_values: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true
